### PR TITLE
Use base_url on android thumbnail

### PR DESCRIPTION
**Pull request by edestecd**
Thumbnails stopped working for me on Android recently and this fixed it

### CODE REVIEW

**Comment by edestecd** [comment]
I'm not sure but it may have something to do with enabling https recently

**Comment by SgtBatten** [comment]
> I'm not sure but it may have something to do with enabling https recently. That or an Android update...

Could you please explain what you mean. Did HA do something or did you do something?

**Comment by edestecd** [comment]
I put a reverse proxy in front of frigate with https. Caddy specifically. B/c of https all the way through absolute urls are required. This should not break http, but feel free to test.

**Comment by SgtBatten** [comment]
I also have reverse proxies on all my services. Via nginx through swag. 

However they are not used internally. So when configuring the home assistant frigate integration I still just use the http Lan IP and port. Did you use something else there?

**Comment by edestecd** [comment]
I use https internally as well as I have multiple locations with frigate and although I'm using a vpn its still not on the same box so I prefer to use https everywhere.

**Comment by edestecd** [comment]
In other words when configuring the home assistant integration I go through the proxy and use https. Everything else works as it should except this so I went investigating and this fixed it.

**Comment by edestecd** [comment]
Can you verify this change continues to work in your setup? If so then we have a config that works for both and I think its good for all

**Comment by SgtBatten** [comment]
Adding baseurl would work for all. I'm unsure if it introduces inefficiencies in delivery of images and videos though

**Review by SgtBatten — APPROVED** [review]

**Pull request merged**
