### PR TITLE
Change camera name to lowercase in api call

### PR DESCRIPTION
**Pull request by Gerdna**
I had the issue that the View Stream action did not worked. I only got an "Not found" as a result. After some investigation, I recognized that I named the Camera with a captial letter ("Driveway") in Frigate. It seems like the API can only handle lowercase camera names.

But maybe it is not a good idea to have the camera named with a capital letter in the beginning. Please let me know if I should rather change my camera name ;).

### CODE REVIEW

**Comment by SgtBatten** [comment]
@Gerdna sorry i missed this. is this working for you?

**Comment by Gerdna** [comment]
@SgtBatten No problem. Yes it works perfectly for me.

**Review by SgtBatten — APPROVED** [review]
looks good

**Comment by SgtBatten** [comment]
closes #47

**Pull request merged**
