### PR TITLE
Presence filter for multiple persons

### PR DESCRIPTION
**Pull request by arpel**
Quick implementation of a multi-person presence filter, tested locally for more than 2 months.

Hope this helps !

### CODE REVIEW

**Comment by MilesTEG1** [comment]
Hello,
Please fix the conflicts, it's very interresting. I need this feature ^^

**Comment by SgtBatten** [comment]
looks good. Have you tested using no presence entities, 1 entity and multiple entities?

An adjustment to the description is required to explain to the user if all presence entities must be not home or just one.

The conflict is just the version number, thats fine. Can you also edit the beta file with the same changes

**Comment by MilesTEG1** [comment]
> looks good. Have you tested using no presence entities, 1 entity and multiple entities?
> 
> 
> 
> An adjustment to the description is required to explain to the user if all presence entities must be not home or just one.
> 
> 
> 
> The conflict is just the version number, thats fine. Can you also edit the beta file with the same changes

Hello @SgtBatten ,
I'm not the author of this PR, @arpel is 🙂

**Comment by SgtBatten** [comment]
Yes i know, you replied so github sent you my message. i did not send it to you specifically.

**Comment by MilesTEG1** [comment]
> Yes i know, you replied so github sent you my message. i did not send it to you specifically. 

Ok I just thought you answered to me. Sorry for my message 😅 
I hope @arpel check is notifications 😄

**Comment by SgtBatten** [comment]
No trouble at all. Thanks

**Comment by arpel** [comment]
> looks good. Have you tested using no presence entities, 1 entity and multiple entities?
> An adjustment to the description is required to explain to the user if all presence entities must be not home or just one.

Yes sorry, my use case is simple : no notification to any of us (at home or not) as soon as someone is at home. 
If at least one person is at home the notification is silenced : yes I've tested with all possible combinations and it triggers correctly.

**Comment by arpel** [comment]
With the same changes in Beta, clearly not tested but it looks that the logic has not changed ... so it should work as in Stable.

**Review by arpel — COMMENTED** [review]
Exactly !

**Review by arpel — COMMENTED** [review]
Not exactly sure what I need to do ;)
It look fine !

**Pull request merged**
