### PR TITLE
Better ordered_zones_match

### PR DESCRIPTION
**Pull request by ivanjx**
Improves #295

### CODE REVIEW

**Comment by SgtBatten** [comment]
Fantastic contribution thanks. 

I'm concerned that partial zone name matches would falsly flag as matches. general the 'in' test allows partial list item matches. so 

['alert'] in ['before_alert'] would be true. 

I have to wonder if a better solution would be something like this

```"{{ ordered_zones|select('equalto', ordered_entered_zones) == ordered_zones }}"```

And it may be necessary to swap the two lists in the test in order to get the order of entry preserved. which would make it

```"{{ ordered_entered_zones|select('equalto', ordered_zones) == ordered_zones }}"```

Both are untested so far.

**Comment by ivanjx** [comment]
i replaced the list comparison using `join` with array intersection. i tested it and it seems to work fine.

**Review by SgtBatten — APPROVED** [review]

**Comment by SgtBatten** [comment]
Could you please add one more change to increment the version number by one letter.

**Comment by ivanjx** [comment]
done

**Review by SgtBatten — APPROVED** [review]

**Pull request merged**
